import Navbar from "@/components/shared/Navbar";
import { valueSansPro } from "./font";
import "./globals.css";

export const metadata = {
  title: "Unlocklive Coffee",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${valueSansPro.className} text-xs text-primary sm:text-sm lg:text-base`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
